package bysj.domain.po;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table searchhistory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SearchhistoryPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchhistory.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchhistory.whatInput
     *
     * @mbg.generated
     */
    private String whatinput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchhistory.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column searchhistory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table searchhistory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchhistory.uid
     *
     * @return the value of searchhistory.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchhistory.uid
     *
     * @param uid the value for searchhistory.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchhistory.whatInput
     *
     * @return the value of searchhistory.whatInput
     *
     * @mbg.generated
     */
    public String getWhatinput() {
        return whatinput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchhistory.whatInput
     *
     * @param whatinput the value for searchhistory.whatInput
     *
     * @mbg.generated
     */
    public void setWhatinput(String whatinput) {
        this.whatinput = whatinput == null ? null : whatinput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchhistory.time
     *
     * @return the value of searchhistory.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchhistory.time
     *
     * @param time the value for searchhistory.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column searchhistory.id
     *
     * @return the value of searchhistory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column searchhistory.id
     *
     * @param id the value for searchhistory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchhistory
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SearchhistoryPO other = (SearchhistoryPO) that;
        return (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getWhatinput() == null ? other.getWhatinput() == null : this.getWhatinput().equals(other.getWhatinput()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchhistory
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getWhatinput() == null) ? 0 : getWhatinput().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchhistory
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", whatinput=").append(whatinput);
        sb.append(", time=").append(time);
        sb.append(", id=").append(id);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}